language: java
sudo: true
jdk:
  - oraclejdk11
  - openjdk11

cache:
  directories:
    - $HOME/.m2

before_install:
  - chmod +x mvnw

script:
  - ./mvnw clean install
  - ./mvnw jacoco:report

after_success:
  - bash <(curl -s https://codecov.io/bash)
